# Serena Project Config — UjuZ API
project_name: "ujuz-api"

languages:
- typescript

encoding: "utf-8"

ignore_all_files_in_gitignore: true

ignored_paths:
- ".next/**"
- ".claude/**"
- ".playwright/**"
- "coverage/**"
- "node_modules/**"
- "mobile/node_modules/**"
- "dist/**"
- "*.log"

read_only: false

excluded_tools: []
included_optional_tools: []
fixed_tools: []

base_modes:
default_modes:

initial_prompt: |
  UjuZ — 어린이집/유치원 입소 AI 서비스. Phase 1~4 완료 (67파일, +9,424줄).

  핵심 아키텍처:
  - Streaming chat: POST /api/bot/chat/stream (contentFilter + checkLimit 통합)
  - 결제: Toss Payments (웹), 딥링크 (앱→웹)
  - 알림: Expo Push + NCP SMS + Email
  - 구독: Free/Basic/Premium, checkLimit 기반 사용량 제한
  - 모바일: Expo SDK 52, 6탭 (홈/검색/지도/채팅/알림/MY)

  협업 모델:
  - Claude Opus 4.6 = 설계/리뷰/통합 (20%)
  - Codex-Spark (gpt-5.3-codex-spark) = 구현 (80%), MCP 연동
  - 대형 작업: 10개 Codex 병렬 → Opus 후처리 → typecheck → commit

  로거 형식: logger.error('메시지', { extra }) — NOT pino-style
  품질 게이트: pnpm typecheck 필수
