# Serena — UjuZ API (minimal config, context in CLAUDE.md)
project_name: "ujuz-api"
languages: [typescript]
encoding: "utf-8"
ignore_all_files_in_gitignore: true
ignored_paths: [".next/**", ".claude/**", "node_modules/**", "mobile/node_modules/**", "dist/**", "docs/**"]
read_only: false
initial_prompt: "UjuZ 어린이집 입소 AI. 모든 컨텍스트는 CLAUDE.md 참조. 별도 메모리 파일 생성 금지."
