# the name by which the project can be referenced within Serena
project_name: "ujuz-api"

languages:
- typescript

encoding: "utf-8"

ignore_all_files_in_gitignore: true

ignored_paths:
- ".next/**"
- ".claude/**"
- ".playwright/**"
- ".playwright-cli/**"
- "coverage/**"
- "*.log"

read_only: false

excluded_tools: []
included_optional_tools: []
fixed_tools: []

base_modes:
default_modes:

initial_prompt: |
  UjuZ API — Next.js 15 App Router + AI SDK v6 + MongoDB Atlas 기반 교육 AI 서비스.

  핵심 아키텍처:
  - Streaming chat: POST /api/bot/chat/stream → createUIMessageStream + streamText
  - Client hook: src/lib/client/hooks/useChat.ts (useAIChat wrapper)
  - State: Zustand store, metadata는 SSE message-metadata 청크로 전달
  - Auth: next-auth v5 beta, OAuth + dev bypass
  - Styling: TailwindCSS v4 + shadcn/ui (new-york), CSS variables

  협업 모델:
  - Claude Opus = 설계/리뷰/아키텍처 (20%)
  - Codex-Spark = 빠른 구현/핫픽스 (80%)
  - TypeScript strict mode 필수, pnpm typecheck 게이트
